//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBooks.WinUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBooks.WinUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezan unos imena i prezimena ili pseudonima!.
        /// </summary>
        public static string Validation_AuthorsName {
            get {
                return ResourceManager.GetString("Validation_AuthorsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravna email adresa!.
        /// </summary>
        public static string Validation_EmailFormat {
            get {
                return ResourceManager.GetString("Validation_EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan format ISBN!.
        /// </summary>
        public static string Validation_ISBN {
            get {
                return ResourceManager.GetString("Validation_ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos je izvan opsega!.
        /// </summary>
        public static string Validation_IzdanjeRange {
            get {
                return ResourceManager.GetString("Validation_IzdanjeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije dozvoljen unos slova!.
        /// </summary>
        public static string Validation_NumberField {
            get {
                return ResourceManager.GetString("Validation_NumberField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedozvoljena dužina unosa! Min 6 znakova max 50!.
        /// </summary>
        public static string Validation_PasswordLength {
            get {
                return ResourceManager.GetString("Validation_PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinke se ne slažu!.
        /// </summary>
        public static string Validation_PasswordProvjera {
            get {
                return ResourceManager.GetString("Validation_PasswordProvjera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan format telefona!.
        /// </summary>
        public static string Validation_PhoneNumberFormat {
            get {
                return ResourceManager.GetString("Validation_PhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan unos! Unesite ispravnu godinu!.
        /// </summary>
        public static string Validation_RangeUntilCurrentYearAttribute {
            get {
                return ResourceManager.GetString("Validation_RangeUntilCurrentYearAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno polje!.
        /// </summary>
        public static string Validation_RequiredField {
            get {
                return ResourceManager.GetString("Validation_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedozvoljena dužina unosa!.
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je zauzeto!.
        /// </summary>
        public static string Validation_Username {
            get {
                return ResourceManager.GetString("Validation_Username", resourceCulture);
            }
        }
    }
}
